version: "2"

run:
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - revive
    - unused
  disable:
    - gochecknoinits
    - gochecknoglobals

  settings:
    govet:
      enable:
        - shadow
    gocritic:
      enabled-checks:
        - appendCombine
        - argOrder
        - badCond
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - hugeParam
        - initClause
        - rangeValCopy
        - sloppyLen
        - typeSwitchVar
        - underef
        - unlambda
        - unslice
    errcheck:
      check-type-assertions: true
      check-blank: true

  exclusions:
    # Match v1 behavior: do not apply the default exclusions.
    presets: []
    paths:
      - ^examples/
    rules:
      - linters:
          - govet
        text: "composite literal uses unkeyed fields"
      - linters:
          - staticcheck
        text: "SA5001: should check returned error before deferring"

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - ^examples/
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/startreedata/pinot-client-go

