//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: pinot/proto/broker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PinotQueryBroker_Submit_FullMethodName = "/org.apache.pinot.common.proto.PinotQueryBroker/Submit"
)

// PinotQueryBrokerClient is the client API for PinotQueryBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinotQueryBrokerClient interface {
	Submit(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrokerResponse], error)
}

type pinotQueryBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewPinotQueryBrokerClient(cc grpc.ClientConnInterface) PinotQueryBrokerClient {
	return &pinotQueryBrokerClient{cc}
}

func (c *pinotQueryBrokerClient) Submit(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrokerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PinotQueryBroker_ServiceDesc.Streams[0], PinotQueryBroker_Submit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BrokerRequest, BrokerResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinotQueryBroker_SubmitClient = grpc.ServerStreamingClient[BrokerResponse]

// PinotQueryBrokerServer is the server API for PinotQueryBroker service.
// All implementations must embed UnimplementedPinotQueryBrokerServer
// for forward compatibility.
type PinotQueryBrokerServer interface {
	Submit(*BrokerRequest, grpc.ServerStreamingServer[BrokerResponse]) error
	mustEmbedUnimplementedPinotQueryBrokerServer()
}

// UnimplementedPinotQueryBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPinotQueryBrokerServer struct{}

func (UnimplementedPinotQueryBrokerServer) Submit(*BrokerRequest, grpc.ServerStreamingServer[BrokerResponse]) error {
	return status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedPinotQueryBrokerServer) mustEmbedUnimplementedPinotQueryBrokerServer() {}
func (UnimplementedPinotQueryBrokerServer) testEmbeddedByValue()                          {}

// UnsafePinotQueryBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PinotQueryBrokerServer will
// result in compilation errors.
type UnsafePinotQueryBrokerServer interface {
	mustEmbedUnimplementedPinotQueryBrokerServer()
}

func RegisterPinotQueryBrokerServer(s grpc.ServiceRegistrar, srv PinotQueryBrokerServer) {
	// If the following call panics, it indicates UnimplementedPinotQueryBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PinotQueryBroker_ServiceDesc, srv)
}

func _PinotQueryBroker_Submit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BrokerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PinotQueryBrokerServer).Submit(m, &grpc.GenericServerStream[BrokerRequest, BrokerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinotQueryBroker_SubmitServer = grpc.ServerStreamingServer[BrokerResponse]

// PinotQueryBroker_ServiceDesc is the grpc.ServiceDesc for PinotQueryBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PinotQueryBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.apache.pinot.common.proto.PinotQueryBroker",
	HandlerType: (*PinotQueryBrokerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Submit",
			Handler:       _PinotQueryBroker_Submit_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pinot/proto/broker.proto",
}
