//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pinot/proto/broker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerRequest) Reset() {
	*x = BrokerRequest{}
	mi := &file_pinot_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerRequest) ProtoMessage() {}

func (x *BrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinot_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerRequest.ProtoReflect.Descriptor instead.
func (*BrokerRequest) Descriptor() ([]byte, []int) {
	return file_pinot_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *BrokerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BrokerRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type BrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerResponse) Reset() {
	*x = BrokerResponse{}
	mi := &file_pinot_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerResponse) ProtoMessage() {}

func (x *BrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinot_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerResponse.ProtoReflect.Descriptor instead.
func (*BrokerResponse) Descriptor() ([]byte, []int) {
	return file_pinot_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *BrokerResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BrokerResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pinot_proto_broker_proto protoreflect.FileDescriptor

const file_pinot_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x18pinot/proto/broker.proto\x12\x1dorg.apache.pinot.common.proto\"\xb6\x01\n" +
	"\rBrokerRequest\x12V\n" +
	"\bmetadata\x18\x01 \x03(\v2:.org.apache.pinot.common.proto.BrokerRequest.MetadataEntryR\bmetadata\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x0eBrokerResponse\x12W\n" +
	"\bmetadata\x18\x01 \x03(\v2;.org.apache.pinot.common.proto.BrokerResponse.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012{\n" +
	"\x10PinotQueryBroker\x12g\n" +
	"\x06Submit\x12,.org.apache.pinot.common.proto.BrokerRequest\x1a-.org.apache.pinot.common.proto.BrokerResponse0\x01B;Z9github.com/startreedata/pinot-client-go/pinot/proto;protob\x06proto3"

var (
	file_pinot_proto_broker_proto_rawDescOnce sync.Once
	file_pinot_proto_broker_proto_rawDescData []byte
)

func file_pinot_proto_broker_proto_rawDescGZIP() []byte {
	file_pinot_proto_broker_proto_rawDescOnce.Do(func() {
		file_pinot_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pinot_proto_broker_proto_rawDesc), len(file_pinot_proto_broker_proto_rawDesc)))
	})
	return file_pinot_proto_broker_proto_rawDescData
}

var file_pinot_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pinot_proto_broker_proto_goTypes = []any{
	(*BrokerRequest)(nil),  // 0: org.apache.pinot.common.proto.BrokerRequest
	(*BrokerResponse)(nil), // 1: org.apache.pinot.common.proto.BrokerResponse
	nil,                    // 2: org.apache.pinot.common.proto.BrokerRequest.MetadataEntry
	nil,                    // 3: org.apache.pinot.common.proto.BrokerResponse.MetadataEntry
}
var file_pinot_proto_broker_proto_depIdxs = []int32{
	2, // 0: org.apache.pinot.common.proto.BrokerRequest.metadata:type_name -> org.apache.pinot.common.proto.BrokerRequest.MetadataEntry
	3, // 1: org.apache.pinot.common.proto.BrokerResponse.metadata:type_name -> org.apache.pinot.common.proto.BrokerResponse.MetadataEntry
	0, // 2: org.apache.pinot.common.proto.PinotQueryBroker.Submit:input_type -> org.apache.pinot.common.proto.BrokerRequest
	1, // 3: org.apache.pinot.common.proto.PinotQueryBroker.Submit:output_type -> org.apache.pinot.common.proto.BrokerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pinot_proto_broker_proto_init() }
func file_pinot_proto_broker_proto_init() {
	if File_pinot_proto_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pinot_proto_broker_proto_rawDesc), len(file_pinot_proto_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pinot_proto_broker_proto_goTypes,
		DependencyIndexes: file_pinot_proto_broker_proto_depIdxs,
		MessageInfos:      file_pinot_proto_broker_proto_msgTypes,
	}.Build()
	File_pinot_proto_broker_proto = out.File
	file_pinot_proto_broker_proto_goTypes = nil
	file_pinot_proto_broker_proto_depIdxs = nil
}
